import { Language } from './types';

export const POSITION_OPTIONS = [
  '前端开发工程师',
  '后端开发工程师',
  '全栈开发工程师',
  'iOS 开发工程师',
  'Android 开发工程师',
  '产品经理',
  'UI/UX 设计师',
  '数据分析师',
  '算法工程师',
  '测试工程师',
  '运维工程师',
  '项目经理',
  '架构师',
  '技术总监',
];

export const INTERVIEW_TYPES = [
  { value: 'technical', labelZh: '技术深挖', labelEn: 'Technical Deep Dive' },
  { value: 'project', labelZh: '项目经验', labelEn: 'Project Experience' },
  { value: 'hr', labelZh: 'HR 行为面', labelEn: 'HR Behavioral' },
  { value: 'stress', labelZh: '压力测试', labelEn: 'Stress Test' },
];

export const STAGE_ORDER = ['intro', 'project', 'technical', 'scenario', 'summary'];

export const STAGE_LABELS: Record<string, { zh: string; en: string }> = {
  intro: { zh: '自我介绍', en: 'Self Introduction' },
  project: { zh: '项目深挖', en: 'Project Deep Dive' },
  technical: { zh: '技术评审', en: 'Technical Assessment' },
  scenario: { zh: '情景追问', en: 'Scenario Follow-up' },
  summary: { zh: '总结收尾', en: 'Closing' },
};

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    nav: {
      home: 'Home',
      create: 'New Interview',
      history: 'History',
      profile: 'Profile',
    },
    hero: {
      tag: 'AI MOCK INTERVIEW',
      title: 'Sharpen your interview skills with AI',
      description: 'AI simulates real interviewer logic, capturing every weakness under pressure. Deep preparation for your next big tech interview.',
      start: 'Start Mock Interview',
    },
    rhythm: {
      title: 'Training Progress',
      status: 'Active',
      readiness: 'Readiness',
      mocksCount: 'Mock Sessions',
      avgScore: 'Average Score',
    },
    tasks: {
      title: 'Training Tasks',
      markDone: 'Mark Done',
      none: 'No pending tasks',
    },
    latest: {
      tag: 'LATEST SESSION',
      title: 'Latest Interview Review',
      strengths: 'Strengths',
      weaknesses: 'Weaknesses',
      suggestions: 'Suggestions',
      noData: 'No interview sessions yet',
    },
    create: {
      title: 'Create Interview',
      description: 'Configure your mock interview session',
      resume: {
        title: 'Resume',
        upload: 'Upload Resume',
        selectExisting: 'Select Existing',
        hint: 'PDF, DOC, DOCX (Max 10MB)',
        modal: {
          title: 'Select Resume',
          confirm: 'Use This',
          cancel: 'Cancel',
        }
      },
      position: 'Target Position',
      positionPlaceholder: 'Select position',
      company: 'Target Company',
      companyPlaceholder: 'e.g. Google, ByteDance...',
      type: 'Interview Type',
      difficulty: 'Difficulty',
      levels: ['JUNIOR', 'MID-LEVEL', 'SENIOR', 'EXPERT', 'FOUNDER'],
      focus: 'Focus Areas',
      focusOptions: ['Product Logic', 'Business Insight', 'Project Management'],
      additional: 'Additional Info',
      additionalPlaceholder: 'Specific scenarios or concerns...',
      submit: 'Start Interview',
    },
    room: {
      title: 'AI Interview',
      progress: 'Interview Progress',
      nextStage: 'Next Stage',
      endSession: 'End Interview',
      aiRole: 'AI Interviewer',
      userRole: 'You',
      hint: 'Hold Space to speak',
      send: 'Send',
      confirmEnd: 'Are you sure you want to end this interview?',
      listening: 'Listening...',
      micOff: 'Mic Off',
      voiceHint: 'Hold Space to speak',
      sttError: 'Recognition failed, please try again',
    },
    auth: {
      login: {
        title: 'Log In',
        subtitle: 'Log in to your account',
        email: 'Email',
        password: 'Password',
        submit: 'Log In',
        errors: {
          invalidEmail: 'Invalid email address',
          weakPassword: 'Password must be at least 8 characters with uppercase, lowercase, and numbers.',
        },
        noAccount: 'No account?',
        registerNow: 'Register',
      },
      register: {
        title: 'Register',
        subtitle: 'Create your account',
        name: 'Name',
        email: 'Email',
        position: 'Target Position',
        positionPlaceholder: 'Select your target position',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        submit: 'Create Account',
        errors: {
          invalidEmail: 'Invalid email address',
          weakPassword: 'Password must be at least 8 characters with uppercase, lowercase, and numbers.',
          passwordMismatch: 'Passwords do not match',
        },
        hasAccount: 'Already have an account?',
        loginNow: 'Log in',
      },
      dropdown: {
        settings: 'Settings',
        logout: 'Log Out',
      },
    },
    report: {
      title: 'Interview Report',
      regenerate: 'Regenerate',
      totalScore: 'Overall Score',
      percentile: 'Better than {{percent}}% candidates',
      metrics: {
        technical: 'Technical',
        expression: 'Communication',
        project: 'Project Depth',
        stability: 'Stability',
      },
      strengths: { title: 'Core Strengths' },
      weaknesses: { title: 'Areas for Improvement' },
      suggestions: { title: 'Suggestions' },
      noData: 'Report not available yet',
      actions: {
        newInterview: 'Start New Interview',
        toHistory: 'View History',
      },
    },
    profile: {
      title: 'Profile',
      subtitle: 'Manage your account and preferences',
      basic: {
        title: 'Basic Info',
        save: 'Save',
        avatarChange: 'Change Avatar',
        name: 'Name',
        email: 'Email',
        target: 'Target Position',
      },
      resume: {
        title: 'My Resumes',
        upload: 'Upload',
        empty: 'No resumes yet',
        duplicateTitle: 'Duplicate Resume Name',
        duplicateMsg: 'A resume named "{name}" already exists. Replace it or cancel?',
        replace: 'Replace',
        cancel: 'Cancel',
      },
      stats: {
        title: 'Statistics',
        total: 'Total Mocks',
        score: 'Avg Score',
      },
      preferences: {
        title: 'Interview Preferences',
        personality: 'AI Interviewer Style',
        personalities: {
          professional: 'Professional & Rigorous',
          encouraging: 'Warm & Encouraging',
          stress: 'Stress Test',
        },
        feedback: 'Feedback Detail',
        feedbackLevels: {
          short: 'Brief',
          medium: 'Medium',
          deep: 'Detailed',
        },
        language: 'Language',
      },
      logout: 'Log Out',
      logoutDesc: 'Log out of your account',
      toast: 'Saved',
    },
    history: {
      title: 'Interview History',
      subtitle: 'Review your past mock interviews and AI feedback',
      searchPlaceholder: 'Search by company or position...',
      type: 'Type',
      status: 'Status',
      search: 'Search',
      allTypes: 'All Types',
      allStatus: 'All Status',
      score: 'Score',
      viewReport: 'View Report',
      continue: 'Continue Interview',
      tryAgain: 'Try Again',
      noResults: 'No interviews yet. Start your first one!',
      createInterview: 'New Interview',
      statusLabels: {
        completed: 'Completed',
        in_progress: 'In Progress',
      },
      pagination: {
        prev: 'Prev',
        next: 'Next',
      },
    },
  },
  zh: {
    nav: {
      home: '首页',
      create: '新建面试',
      history: '历史记录',
      profile: '个人中心',
    },
    hero: {
      tag: 'AI 模拟面试',
      title: '用 AI 训练你的面试能力',
      description: 'AI 模拟真实面试官的追问逻辑，在压力环境下捕捉你的每一处逻辑盲区，深度打磨你的面试表现。',
      start: '开始模拟面试',
    },
    rhythm: {
      title: '训练进度',
      status: '进行中',
      readiness: '准备度',
      mocksCount: '模拟场次',
      avgScore: '平均得分',
    },
    tasks: {
      title: '训练任务',
      markDone: '标记完成',
      none: '暂无训练任务',
    },
    latest: {
      tag: '最近面试',
      title: '最近面试回顾',
      strengths: '优势',
      weaknesses: '弱点',
      suggestions: '建议',
      noData: '还没有面试记录',
    },
    create: {
      title: '创建面试',
      description: '配置你的模拟面试参数',
      resume: {
        title: '简历',
        upload: '上传简历',
        selectExisting: '选择已有简历',
        hint: '支持 PDF、DOC、DOCX (最大 10MB)',
        modal: {
          title: '选择简历',
          confirm: '使用此简历',
          cancel: '取消',
        }
      },
      position: '目标岗位',
      positionPlaceholder: '选择目标岗位',
      company: '目标公司',
      companyPlaceholder: '例如：字节跳动、腾讯...',
      type: '面试类型',
      difficulty: '面试难度',
      levels: ['初级', '中级', '高级', '专家', '创始人级'],
      focus: '侧重方向',
      focusOptions: ['产品逻辑', '商业洞察', '项目管理'],
      additional: '补充信息',
      additionalPlaceholder: '描述特定场景或你最担心的环节...',
      submit: '开始面试',
    },
    room: {
      title: 'AI 面试',
      progress: '面试进度',
      nextStage: '下一阶段',
      endSession: '结束面试',
      aiRole: 'AI 面试官',
      userRole: '你',
      hint: '按住空格说话',
      send: '发送',
      confirmEnd: '确定要结束本次面试吗？',
      listening: '正在聆听...',
      micOff: '麦克风未开启',
      voiceHint: '按住空格说话',
      sttError: '识别失败，请重新说',
    },
    auth: {
      login: {
        title: '登录',
        subtitle: '登录你的账户',
        email: '电子邮箱',
        password: '密码',
        submit: '登录',
        errors: {
          invalidEmail: '请输入有效的邮箱地址',
          weakPassword: '密码需至少8个字符，含大小写字母和数字',
        },
        noAccount: '没有账户？',
        registerNow: '免费注册',
      },
      register: {
        title: '注册',
        subtitle: '创建你的账户',
        name: '姓名',
        email: '电子邮箱',
        position: '目标岗位',
        positionPlaceholder: '选择目标岗位',
        password: '密码',
        confirmPassword: '确认密码',
        submit: '创建账户',
        errors: {
          invalidEmail: '请输入有效的邮箱地址',
          weakPassword: '密码需至少8个字符，含大小写字母和数字',
          passwordMismatch: '两次输入的密码不一致',
        },
        hasAccount: '已有账户？',
        loginNow: '登录',
      },
      dropdown: {
        settings: '设置',
        logout: '退出登录',
      },
    },
    report: {
      title: '面试报告',
      regenerate: '重新生成',
      totalScore: '综合评分',
      percentile: '超过 {{percent}}% 的候选人',
      metrics: {
        technical: '技术能力',
        expression: '沟通表达',
        project: '项目深度',
        stability: '稳定性',
      },
      strengths: { title: '核心优势' },
      weaknesses: { title: '待改进项' },
      suggestions: { title: '改进建议' },
      noData: '报告尚未生成',
      actions: {
        newInterview: '开始新面试',
        toHistory: '查看历史',
      },
    },
    profile: {
      title: '个人中心',
      subtitle: '管理账户信息和面试偏好',
      basic: {
        title: '基本信息',
        save: '保存',
        avatarChange: '更换头像',
        name: '姓名',
        email: '电子邮箱',
        target: '目标岗位',
      },
      resume: {
        title: '我的简历',
        upload: '上传简历',
        empty: '暂无简历',
        duplicateTitle: '简历名称重复',
        duplicateMsg: '已存在同名简历「{name}」，是否替换原有简历？',
        replace: '替换',
        cancel: '取消',
      },
      stats: {
        title: '训练统计',
        total: '模拟场次',
        score: '平均得分',
      },
      preferences: {
        title: '面试偏好',
        personality: 'AI 面试官风格',
        personalities: {
          professional: '严谨专业',
          encouraging: '亲和鼓励',
          stress: '压力测试',
        },
        feedback: '反馈详细程度',
        feedbackLevels: {
          short: '精简',
          medium: '中等',
          deep: '深度',
        },
        language: '语言',
      },
      logout: '退出登录',
      logoutDesc: '退出当前账户',
      toast: '已保存',
    },
    history: {
      title: '面试历史',
      subtitle: '查看过去的模拟面试记录和 AI 反馈',
      searchPlaceholder: '搜索公司或岗位...',
      type: '面试类型',
      status: '状态',
      search: '查询',
      allTypes: '全部类型',
      allStatus: '全部状态',
      score: '评分',
      viewReport: '查看报告',
      continue: '继续面试',
      tryAgain: '再次尝试',
      noResults: '暂无面试记录，开始你的第一次模拟吧！',
      createInterview: '新建面试',
      statusLabels: {
        completed: '已完成',
        in_progress: '进行中',
      },
      pagination: {
        prev: '上一页',
        next: '下一页',
      },
    },
  },
};